from typing import Optional, Any, Literal

from pydantic import BaseModel


class QueryPlan(BaseModel):
    """
    Structured representation of a user query.
    Generated by the LLM and validated before execution.
    """

    operation: Literal[
        "aggregate",
        "top_n",
        "top_1",
        "trend",
        "compare",
        "out_of_scope"
    ]

    crop: str = ""

    metric: Literal[
        "AREA",
        "PRODUCTION",
        "YIELD"
    ] = "PRODUCTION"

    year: Optional[int] = None

    state: Optional[str] = None

    district: Optional[str] = None

    compare_with: Optional[str] = None

    top_n: Optional[int] = None

    group_by: Literal[
        "State Name",
        "Dist Name",
        "Year"
    ] = "State Name"


class ExecutionResult(BaseModel):

    result_data: Any

    preview_data: Any

    metric_column: str

    chart_type: Optional[str] = None

    summary: dict

    query_context: dict = {}


class FinalResponse(BaseModel):

    answer: str

    chart_path: Optional[str] = None

    query_plan: dict

    provenance: dict

    result_preview: Any